# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('recordTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vName', models.CharField(max_length=30)),
                ('vAccount', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=250)),
                ('area', models.CharField(max_length=30)),
                ('tags', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('qrCode', models.ImageField(upload_to='uploads/qrCodes/')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechat.VAccount'),
        ),
    ]
