# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0002_vaccount_vqq'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccount',
            name='crawl_url',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
