# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0003_vaccount_crawl_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccount',
            name='id',
        ),
        migrations.AlterField(
            model_name='vaccount',
            name='vAccount',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
