# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0004_auto_20170504_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccount',
            name='avatar',
            field=models.ImageField(default='', upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vaccount',
            name='qrCode',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
