# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0005_auto_20170504_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='recordTime',
            new_name='recordDate',
        ),
    ]
